# Practice Lab

# Part 1

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from public_tests import *
from utils import *

%matplotlib inline

In [5]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

In [6]:
print("First few elements of X_train:\n", X_train[:5])
print("Type of X_train:",type(X_train))

First few elements of X_train:
 [[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]]
Type of X_train: <class 'numpy.ndarray'>


In [7]:
print("First few elements of y_train:", y_train[:5])
print("Type of y_train:",type(y_train))

First few elements of y_train: [1 1 0 0 1]
Type of y_train: <class 'numpy.ndarray'>


In [8]:
print ('The shape of X_train is:', X_train.shape)
print ('The shape of y_train is: ', y_train.shape)
print ('Number of training examples (m):', len(X_train))

The shape of X_train is: (10, 3)
The shape of y_train is:  (10,)
Number of training examples (m): 10


# EX 1

In [9]:
import numpy as np

def compute_entropy(y):
    total_examples = len(y)
    num_edible = np.sum(y)
    num_poisonous = total_examples - num_edible
    p_edible = num_edible / total_examples
    p_poisonous = num_poisonous / total_examples
    if p_edible == 0 or p_poisonous == 0:
        entropy = 0 
    else:
        entropy = -p_edible * np.log2(p_edible) - p_poisonous * np.log2(p_poisonous)
    
    return entropy


In [10]:
# Compute entropy at the root node (i.e. with all examples)
# Since we have 5 edible and 5 non-edible mushrooms, the entropy should be 1"

print("Entropy at root node: ", compute_entropy(y_train)) 

# UNIT TESTS
compute_entropy_test(compute_entropy)

Entropy at root node:  1.0
 All tests passed.


# EX 2

In [11]:
def split_dataset(X, node_indices, feature):
  # You need to return the following variables correctly
    left_indices = []
    right_indices = []
    
    for index in node_indices:
        if X[index][feature] == 1:
            left_indices.append(index)
        else:
            right_indices.append(index)
    
    return left_indices, right_indices


In [12]:
root_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Feel free to play around with these variables
# The dataset only has three features, so this value can be 0 (Brown Cap), 1 (Tapering Stalk Shape) or 2 (Solitary)
feature = 0

left_indices, right_indices = split_dataset(X_train, root_indices, feature)

print("Left indices: ", left_indices)
print("Right indices: ", right_indices)

# Visualize the split 
generate_split_viz(root_indices, left_indices, right_indices, feature)

# UNIT TESTS    
split_dataset_test(split_dataset)

Left indices:  [0, 1, 2, 3, 4, 7, 9]
Right indices:  [5, 6, 8]


FileNotFoundError: [Errno 2] "dot" not found in path.

# EX 3

In [13]:
def compute_information_gain(X, y, node_indices, feature):
    # Split dataset
    left_indices, right_indices = split_dataset(X, node_indices, feature)
    
    orig_entropy = compute_entropy(y[node_indices])
    left_w = len(left_indices) / len(node_indices)
    right_w = len(right_indices) / len(node_indices)
    w_avg_entropy = (
        left_w * compute_entropy(y[left_indices]) +
        right_w * compute_entropy(y[right_indices])
    )
    information_gain = orig_entropy - w_avg_entropy
    
    return information_gain

In [23]:
info_gain0 = compute_information_gain(X_train, y_train, root_indices, feature=0)
print("Information Gain from splitting the root on brown cap: ", info_gain0)

info_gain1 = compute_information_gain(X_train, y_train, root_indices, feature=1)
print("Information Gain from splitting the root on tapering stalk shape: ", info_gain1)

info_gain2 = compute_information_gain(X_train, y_train, root_indices, feature=2)
print("Information Gain from splitting the root on solitary: ", info_gain2)

# UNIT TESTS
compute_information_gain_test(compute_information_gain)

Information Gain from splitting the root on brown cap:  0.034851554559677034
Information Gain from splitting the root on tapering stalk shape:  0.12451124978365313
Information Gain from splitting the root on solitary:  0.2780719051126377


/var/folders/6n/zr58hzps4cz7_n89qjnrzb5w0000gr/T/ipykernel_54464/1900070223.py:22: RuntimeWarning: invalid value encountered in scalar divide
  p_edible = num_edible / total_examples
/var/folders/6n/zr58hzps4cz7_n89qjnrzb5w0000gr/T/ipykernel_54464/1900070223.py:23: RuntimeWarning: invalid value encountered in scalar divide
  p_poisonous = num_poisonous / total_examples


AssertionError: Wrong information gain. Expected 0.0 got: nan

# EX 4

In [14]:
def get_best_split(X, y, node_indices):
    # Some useful variables
    num_features = X.shape[1]
    best_information_gain = 0 
    best_feature = -1
    
    for feature in range(num_features):
        information_gain = compute_information_gain(X, y, node_indices, feature)
        if information_gain > best_information_gain:
            best_information_gain = information_gain
            best_feature = feature
    
    return best_feature


In [15]:
best_feature = get_best_split(X_train, y_train, root_indices)
print("Best feature to split on: %d" % best_feature)

# UNIT TESTS
get_best_split_test(get_best_split)

Best feature to split on: 2
 All tests passed.


/var/folders/6n/x3652qj92pv8yrnwqytnq3d40000gn/T/ipykernel_26103/3073486769.py:7: RuntimeWarning: invalid value encountered in long_scalars
  p_edible = num_edible / total_examples
/var/folders/6n/x3652qj92pv8yrnwqytnq3d40000gn/T/ipykernel_26103/3073486769.py:8: RuntimeWarning: invalid value encountered in long_scalars
  p_poisonous = num_poisonous / total_examples


In [16]:
# Not graded
tree = []

def build_tree_recursive(X, y, node_indices, branch_name, max_depth, current_depth):
    """
    Build a tree using the recursive algorithm that split the dataset into 2 subgroups at each node.
    This function just prints the tree.
    
    Args:
        X (ndarray):            Data matrix of shape(n_samples, n_features)
        y (array like):         list or ndarray with n_samples containing the target variable
        node_indices (ndarray): List containing the active indices. I.e, the samples being considered in this step.
        branch_name (string):   Name of the branch. ['Root', 'Left', 'Right']
        max_depth (int):        Max depth of the resulting tree. 
        current_depth (int):    Current depth. Parameter used during recursive call.
   
    """ 

    # Maximum depth reached - stop splitting
    if current_depth == max_depth:
        formatting = " "*current_depth + "-"*current_depth
        print(formatting, "%s leaf node with indices" % branch_name, node_indices)
        return
   
    # Otherwise, get best split and split the data
    # Get the best feature and threshold at this node
    best_feature = get_best_split(X, y, node_indices) 
    
    formatting = "-"*current_depth
    print("%s Depth %d, %s: Split on feature: %d" % (formatting, current_depth, branch_name, best_feature))
    
    # Split the dataset at the best feature
    left_indices, right_indices = split_dataset(X, node_indices, best_feature)
    tree.append((left_indices, right_indices, best_feature))
    
    # continue splitting the left and the right child. Increment current depth
    build_tree_recursive(X, y, left_indices, "Left", max_depth, current_depth+1)
    build_tree_recursive(X, y, right_indices, "Right", max_depth, current_depth+1)

In [17]:
build_tree_recursive(X_train, y_train, root_indices, "Root", max_depth=2, current_depth=0)
generate_tree_viz(root_indices, y_train, tree)

 Depth 0, Root: Split on feature: 2
- Depth 1, Left: Split on feature: 0
  -- Left leaf node with indices [0, 1, 4, 7]
  -- Right leaf node with indices [5]
- Depth 1, Right: Split on feature: 1
  -- Left leaf node with indices [8]
  -- Right leaf node with indices [2, 3, 6, 9]


/var/folders/6n/x3652qj92pv8yrnwqytnq3d40000gn/T/ipykernel_26103/3073486769.py:7: RuntimeWarning: invalid value encountered in long_scalars
  p_edible = num_edible / total_examples
/var/folders/6n/x3652qj92pv8yrnwqytnq3d40000gn/T/ipykernel_26103/3073486769.py:8: RuntimeWarning: invalid value encountered in long_scalars
  p_poisonous = num_poisonous / total_examples


FileNotFoundError: [Errno 2] "dot" not found in path.